Feature/#1 -  Implementação do serviço de cadastro de serviços
petshop-system/petshop-admin-api pull request #2
Opened 2024-06-21 20:23 UTC by gustavojustino

Contexto: Adiciona um novo serviço para gerenciar o cadastro de serviços na aplicação Petshop Admin.
Objetivo: Permitir aos usuários criar novos serviços com nome, preço, descrição e status de ativação.

Funcionalidades Adicionadas:
- Implementação da lógica de negócios para validação de dados.
- Integração com o repositório JPA para persistência de dados.

Alterações Realizadas:
- Adicionado novo método create na classe ServiceService para criação de serviços.
- Modificado ServiceDomain para adicionar validações de entrada.

Impactos Potenciais: 
- Nenhuma mudança significativa no sistema existente, além da adição de novas funcionalidades.

Revisão:
@MaironCosta  @lechitz @mateusrlopez

2024-06-22 00:13 UTC, MaironCosta requested changes

2024-06-22 00:13 UTC, MaironCosta commented on src/main/java/com/petshopadmin/adapter/input/http/ServiceController.java
> +        ServiceDomain serviceDomain = new ServiceDomain();
Ver como está na auth-api para evitar replicação de código e excesso de código que suporte e que poluem a leitura. Veja sobre ConverterMapper.

2024-06-22 00:13 UTC, MaironCosta commented on src/main/java/com/petshopadmin/adapter/output/repository/database/ServiceDatabase.java
> +    public ServiceDatabase(ServiceDomain serviceDomain) {
Ver como está na auth-api para evitar replicação de código e excesso de código que suporte e que poluem a leitura. Veja sobre ConverterMapper.

2024-06-22 00:13 UTC, MaironCosta commented on src/main/java/com/petshopadmin/adapter/output/repository/database/ServiceRepositoryDatabase.java
> +        if (serviceDomain.getContract() != null && serviceDomain.getContract().getId() != null) {
Use o `ObjectUtils` para checar se é nulo ou vazio. Ver ServiceService.getByID.

2024-06-22 00:13 UTC, MaironCosta commented on src/main/java/com/petshopadmin/application/service/ServiceService.java
> +    static String ILLEGAL_ARGUMENT_NAME_EXCEPTION = "name cannot be null or empty";
👍

2024-06-22 00:13 UTC, MaironCosta commented on src/main/java/com/petshopadmin/application/service/ServiceService.java
> +    @Transactional
@Transaction: qual a necessidade? Foi necessário?

2024-06-22 00:13 UTC, MaironCosta commented on src/main/java/com/petshopadmin/application/service/ServiceService.java
> +        if (ObjectUtils.isEmpty(serviceDomain)) {
Separar bloco de validação num método diferente. Ver petshop-api.

2024-06-22 00:13 UTC, MaironCosta commented on src/main/java/com/petshopadmin/application/service/ServiceService.java
> +        if (Objects.isNull(serviceDomain.getDescription()) || serviceDomain.getDescription().trim().isEmpty()) {
Usar ObjectUtils.isEmpty ou ObjectUtils.isNonEmpty. No outros também.

2024-06-22 00:13 UTC, MaironCosta commented on src/main/java/com/petshopadmin/application/service/ServiceService.java
> +
Pra que tudo isso de espaço?

2024-06-22 00:13 UTC, MaironCosta commented on src/main/java/com/petshopadmin/exception/GlobalExceptionHandler.java
> +    public final ResponseEntity<ApiError> handleIllegalArgumentException(IllegalArgumentException ex, WebRequest request) {
Topzera da balada. Legal que tu entendeu isso.

2024-06-22 00:14 UTC, MaironCosta commented
Faltaram os testes.

2024-06-22 05:17 UTC, gustavojustino commented on src/main/java/com/petshopadmin/application/service/ServiceService.java
> +    @Transactional
Mestre, aqui uma leve subjectividade, quando estamos trabalhando com inserção de dados, neste caso, uma operação de escrita, precisamos manter a consistência e atomicidade destes dados, não é apropriado o uso da anotation @Transactional, garantindo que o estado do sistema permaneça consistente em caso de falhas? Abraços!

2024-06-24 22:57 UTC, gustavojustino commented
As solicitações de alterações foram feitas até o presente momento, aguardando o review sobre os novos commits! Abç.

2024-06-27 23:58 UTC, lechitz approved these changes

2024-06-29 14:44 UTC, MaironCosta requested changes
Aplicar correções citadas.

2024-06-29 14:44 UTC, MaironCosta commented on src/main/java/com/petshopadmin/adapter/input/http/ServiceController.java
> +    @PostMapping(path = "/create", produces = MediaType.APPLICATION_JSON_VALUE)
Poderia deixar somente o `/`, tirar o `/create`. É Rest, pode-se utilizar o verbo do request, tais como `POST`, `DELETE`, `PUT`, `GET`, ...

https://developer.mozilla.org/pt-BR/docs/Web/HTTP/Methods

2024-06-29 14:44 UTC, MaironCosta commented on src/main/java/com/petshopadmin/adapter/output/repository/database/ServiceDatabase.java
> +    public ServiceDatabase(ServiceDomain serviceDomain) {
Não foi possível o Mapper?

2024-06-29 14:44 UTC, MaironCosta commented on src/main/java/com/petshopadmin/adapter/input/http/ServiceRequestHTTP.java
> +                                 boolean active, String description, Long contractId) implements Serializable { }
No projeto para payloads nós estamos usando snak case o camel case? Seria bom manter o padrão.

2024-06-29 14:44 UTC, MaironCosta commented on src/main/java/com/petshopadmin/application/service/ServiceService.java
> +    @Transactional
O caso é, quantas operações transacionais e correlacionadas estão sendo feitas neste método? Eu creio que só uma transação e sem relação com outra transação, ou seja, somente uma única transação.

Mas por mim pode deixar. Eu só perguntei para saber se tu sabia o que estava fazendo.

---

A anotação `@Transactional` é usada quando você deseja que determinado método/classe seja executado em uma transação.

Vamos supor que o usuário A queira transferir R$100 para o usuário B. O que acontece é:

1) Diminuímos a conta de A em R$100;
2) Adicionamos R$100 à conta de B;

Vamos supor que a exceção seja lançada após executar 1) e antes de executar 2). Agora nós teríamos algum tipo de inconsistência porque A perdeu R$100 enquanto B não conseguiu nada. Transações significa tudo ou nada. Se houver uma exceção lançada em algum lugar do método, as alterações não persistirão no banco de dados. Acontece algo chamado _rollback_.

Se você não especificar @Transacional, cada chamada de banco de dados estará em uma transação diferente.

2024-06-29 14:44 UTC, MaironCosta commented on src/main/java/com/petshopadmin/application/service/ServiceService.java
> +    private void validateServiceDomain(ServiceDomain serviceDomain) throws InternalServerErrorException, IllegalArgumentException, NotFoundException {
Coloque o método numa interface e o exponha a um endpoint http. Veja como será o fluxo no projeto bff-mobile, talvez lhe ajude a ter uma visão de como funcionará.

Talvez o melhor a ser feito aqui seja guardar numa lista todos os erros que ocorreram e lançar uma exception ao final com a lista de erros, talvez seja melhor mostrar todos os erros de uma única vez do que ficar dando erro a todo momento.

2024-06-29 14:44 UTC, MaironCosta commented on src/main/java/com/petshopadmin/utils/converter/ServiceConverterMapperImpl.java
> +    public ServiceDomain toServiceDomain(ServiceRequestHTTP source) {
No projeto `auth-api` está assim? Precisou ser assim? Se sim, qual o motivo?

Veja:

```
AuthController.save
...

AuthenticationDomain authenticationDomain = authenticationConverterMapper
                .toAuthenticationDomain(authenticationProxyService.create(apd));
...

```

2024-06-29 14:44 UTC, MaironCosta commented on src/test/java/com/petshopadmin/application/service/ServiceServiceTest.java
> +    @Test
Os testes ficaram legais. Pra quem não sabia ficaram bem bom. Mandou bem, meu caro!!!!!!!!

2024-07-02 15:18 UTC, MatheusFerreiraZx approved these changes

2024-07-07 18:18 UTC, MaironCosta requested changes
Ajustar validação para cadastrar um novo serviço. 

1) A interface `ServiceUserCase` serve para atender aos casos de uso de Serviço;
2) Inexiste endpoint para validar o caso de uso de validação de um novo Serviço;

Buscar um contrato no repositório de um outro "domínio" está errado neste contexto. Faça a busca por um Contrato dentro do controller e passe este objeto pra frente. Ou seja, busque no _ServiceController_ pelo _Contrato_ informado, passe esse contrato pro objeto que será cadastrado/validado, neste caso, o objeto de serviço.

2024-07-07 18:18 UTC, MaironCosta commented on src/main/java/com/petshopadmin/adapter/output/repository/database/ServiceRepositoryDatabase.java
> +    public ServiceRepositoryDatabase (ServiceJPARepository serviceJPARepository, ContractJPARepository contractJPARepository, ServiceConverterMapper serviceConverterMapper) {
Ao invés de pegar o "contrato" no repository do service, recupere no controller do serviço e repasse ao restante do processo.

2024-07-07 18:18 UTC, MaironCosta commented on src/main/java/com/petshopadmin/application/port/input/ServiceValidation.java
> +    void validateServiceDomain (ServiceDomain serviceDomain) throws InternalServerErrorException, IllegalArgumentException, NotFoundException;
Pra que essa interface com essa validação? Já existe a interface `ServiceUserCase`.

2024-07-07 18:18 UTC, MaironCosta commented on src/main/java/com/petshopadmin/application/service/ValidationService.java
> +package com.petshopadmin.application.service;
Existe o `ServiceUserCase` que é onde deveria ficar essa validação. Como dito anteriormente, era para colocar o método de validação na interface e o expor a um request http para prover uma forma do client solicitar uma validação dos dados. 

Isso é um caso de uso, um UserCase, um `ServiceUserCase`. A interface `ServiceUserCase` existe pra isso, expor os casos de uso referentes ao Serviço.

2024-07-07 18:18 UTC, MaironCosta commented on src/main/java/com/petshopadmin/utils/converter/ServiceConverterMapper.java
> +public interface ServiceConverterMapper {
Ficou maneiro!

2024-07-07 18:18 UTC, MaironCosta commented on src/main/java/com/petshopadmin/utils/converter/ServiceConverterMapper.java
> +public interface ServiceConverterMapper {
Funcionaria se colocasse um pra `ServiceRequestHTTP` e um pro `ServiceResponseHTTP`?

2024-07-07 18:18 UTC, MaironCosta commented on src/test/java/com/petshopadmin/application/service/ServiceServiceTest.java
> +        ServiceDomain invalidDescription = new ServiceDomain();
Faça um teste para _Name_ e outro para _Description_.

2024-07-07 18:50 UTC, MaironCosta commented on src/main/java/com/petshopadmin/application/service/ValidationService.java
> +        if (ObjectUtils.isEmpty(serviceDomain.getName().trim())) {
Aqui é passível de `NullPointerException`. Realizar o devido tratamento e melhorar o código!

https://pt.stackoverflow.com/questions/63617/o-que-%C3%A9-a-nullpointerexception-e-quais-s%C3%A3o-suas-principais-causas

PS.: Vale para as demais validações.

2024-07-14 08:45 UTC, gustavojustino commented on src/main/java/com/petshopadmin/adapter/output/repository/database/ServiceRepositoryDatabase.java
> +    public ServiceRepositoryDatabase (ServiceJPARepository serviceJPARepository, ContractJPARepository contractJPARepository, ServiceConverterMapper serviceConverterMapper) {
A única lógica que consegui pensar para isso é recuperando o id pelo DTO e atribuindo em contractDomain,  por favor, se não fizer sentido, peço nova revisão!

2024-07-14 08:45 UTC, gustavojustino commented
> Ajustar validação para cadastrar um novo serviço.
> 
> 1. A interface `ServiceUserCase` serve para atender aos casos de uso de Serviço;
> 2. Inexiste endpoint para validar o caso de uso de validação de um novo Serviço;
> 
> Buscar um contrato no repositório de um outro "domínio" está errado neste contexto. Faça a busca por um Contrato dentro do controller e passe este objeto pra frente. Ou seja, busque no _ServiceController_ pelo _Contrato_ informado, passe esse contrato pro objeto que será cadastrado/validado, neste caso, o objeto de serviço.

2024-07-14 08:46 UTC, gustavojustino commented on src/main/java/com/petshopadmin/application/port/input/ServiceValidation.java
> +    void validateServiceDomain (ServiceDomain serviceDomain) throws InternalServerErrorException, IllegalArgumentException, NotFoundException;
Peço perdão, foi corrigido e peço nova revisão para ServiceUserCase!

2024-07-14 08:47 UTC, gustavojustino commented on src/main/java/com/petshopadmin/application/service/ValidationService.java
> +package com.petshopadmin.application.service;
Foi implemetado o método de validação na interface de casos de uso em Serviceusercase, a validação ocorre durante a requisição ? deveria ser exposta no próprio método de criação como propriamente feito?

2024-07-14 08:48 UTC, gustavojustino commented on src/main/java/com/petshopadmin/utils/converter/ServiceConverterMapper.java
> +public interface ServiceConverterMapper {
Deverá haver Mapper para tratar exclusivamente de Contract?

2024-07-14 08:49 UTC, gustavojustino commented on src/test/java/com/petshopadmin/application/service/ServiceServiceTest.java
> +        ServiceDomain invalidDescription = new ServiceDomain();
É pra já !

2024-07-14 08:50 UTC, gustavojustino commented on src/main/java/com/petshopadmin/application/service/ValidationService.java
> +        if (ObjectUtils.isEmpty(serviceDomain.getName().trim())) {
É pra já !

2024-07-14 08:50 UTC, gustavojustino commented on src/main/java/com/petshopadmin/utils/converter/ServiceConverterMapper.java
> +public interface ServiceConverterMapper {
Vou verificar, são 05:50 da manha neste exato momento, volto com essa informação logo

2024-07-14 22:24 UTC, gustavojustino commented on src/main/java/com/petshopadmin/utils/converter/ServiceConverterMapper.java
> +public interface ServiceConverterMapper {
Teria que restruturar algumas coisas, pois  ao tentar utilizar o ServiceResponseHTTP é retornado HttpMessageConversionException, acredito que não pode ser serializado.

2024-07-14 22:36 UTC, gustavojustino commented on src/main/java/com/petshopadmin/adapter/output/repository/database/ServiceRepositoryDatabase.java
> +    public ServiceRepositoryDatabase (ServiceJPARepository serviceJPARepository, ContractJPARepository contractJPARepository, ServiceConverterMapper serviceConverterMapper) {
Refatorado, a lógica para pegar o contrato é recuperá-lo no momento em que o cliente criar o serviço, associar o contrato mapeado pelo converter mapper no serviço (servicedomain), validá-lo e criar o serviço.

2024-07-15 02:34 UTC, gustavojustino commented on src/test/java/com/petshopadmin/application/service/ServiceServiceTest.java
> +        ServiceDomain invalidDescription = new ServiceDomain();
Foram feitos testes para nomes e descrição, assim como foram adicionados novos testes unitários

2024-07-15 02:36 UTC, gustavojustino commented on src/main/java/com/petshopadmin/application/service/ValidationService.java
> +        if (ObjectUtils.isEmpty(serviceDomain.getName().trim())) {
Foram feitos tratamentos para evitar NullPointerException em atributos que possam vir nulos ou própriamente o objeto desses atributos, gerando NullPointerException

2024-07-15 06:58 UTC, gustavojustino commented
Foram feitas diversas modificações neste pull request, aguardo novas revisões. Obrigado.

2024-07-17 02:47 UTC, MaironCosta requested changes
Muitos if vazios; validação precisa ser colocada dentro de Service; e outros citados.

2024-07-17 02:47 UTC, MaironCosta commented on src/main/java/com/petshopadmin/adapter/input/http/ServiceController.java
> +    @PostMapping(value = "/validate", produces = MediaType.APPLICATION_JSON_VALUE)
Está dentro do padrão dos demais? Confirme vendo as rotas no `petshop-api`.

2024-07-17 02:47 UTC, MaironCosta commented on src/main/java/com/petshopadmin/application/service/ServiceService.java
> +    public ServiceService (ServiceRepositoryDatabase serviceRepositoryDatabase, ValidationService validationService) {
Se a interface `ServiceUserCase` tem o método de validação, qual o sentido de ter esse `ValidationService`?

2024-07-17 02:47 UTC, MaironCosta commented on src/main/java/com/petshopadmin/application/service/ServiceService.java
> +        validationService.validate(serviceDomain);
Coloque o código de validação aqui dentro.

2024-07-17 02:47 UTC, MaironCosta commented on src/main/java/com/petshopadmin/application/service/ServiceService.java
> +        validationService.validate(serviceDomain);
Se tem esse _validate_ aqui neste ponto, por qual motivo de também estar no _controller_?

2024-07-17 02:47 UTC, MaironCosta commented on src/main/java/com/petshopadmin/application/service/ValidationService.java
> +public class ValidationService  {
Coloque toda a implementação dentro do _Service_.

2024-07-17 02:47 UTC, MaironCosta commented on src/main/java/com/petshopadmin/application/service/ValidationService.java
> +        if (ObjectUtils.allNotNull(serviceDomain, serviceDomain.getName()) &&
Qual sentido de ter `if` vazio?

2024-07-17 02:47 UTC, MaironCosta commented on src/main/java/com/petshopadmin/application/service/ValidationService.java
> +        if (ObjectUtils.allNotNull(serviceDomain, serviceDomain.getPrice()) && serviceDomain.getPrice().compareTo(BigDecimal.ZERO) > 0) {
Qual sentido de ter `if` vazio?

2024-07-17 02:47 UTC, MaironCosta commented on src/main/java/com/petshopadmin/application/service/ValidationService.java
> +        if (ObjectUtils.isNotEmpty(serviceDomain) && serviceDomain.isActive()) {
Qual sentido de ter `if` vazio?

2024-07-17 02:47 UTC, MaironCosta commented on src/main/java/com/petshopadmin/application/service/ValidationService.java
> +        if (serviceDomain != null && serviceDomain.getDescription() != null && !serviceDomain.getDescription().trim().isEmpty()) {
Por qual motivo deixou de usar o `ObjectUtils.allNotNull`?

2024-07-17 02:47 UTC, MaironCosta commented on src/main/java/com/petshopadmin/application/service/ValidationService.java
> +        if (ObjectUtils.allNotNull(serviceDomain, serviceDomain.getDescription()) &&
Qual sentido de ter `if` vazio?

2024-07-17 02:47 UTC, MaironCosta commented on src/main/java/com/petshopadmin/application/service/ValidationService.java
> +        if (ObjectUtils.isNotEmpty(serviceDomain.getContract().getId())) {
Qual sentido de ter `if` vazio?

2024-07-17 02:47 UTC, MaironCosta commented on src/main/java/com/petshopadmin/configuration/ServiceConfiguration.java
> +    public ServiceConverterMapper serviceConverterMapper() {
No _petshop-auth_ precisou disso?

2024-07-17 02:47 UTC, MaironCosta commented on src/main/java/com/petshopadmin/configuration/ServiceConfiguration.java
> +    public ContractRepositoryDatabase contractRepositoryDatabase(ContractJPARepository contractJPARepository, ServiceConverterMapper serviceConverterMapper) {
Ta no lugar errado!

2024-07-17 05:01 UTC, gustavojustino commented on src/main/java/com/petshopadmin/application/service/ServiceService.java
> +    public ServiceService (ServiceRepositoryDatabase serviceRepositoryDatabase, ValidationService validationService) {
Foi uma interpretação equivocada que eu tive a cerca da sua orientação, anteriormente você tinha pedido para remover o método Validate dentro de Service e implementar a entradadeste método pelo ServiceUserCase e posteriormente expor isto no endpoint, entendendo que o pilar principal, é o desacoplamento, no momento acreditei que você queria separar este método da classe de Serviço, e acabei criando um service para Validation(erradamente) (mesmo subentendendo que validate é um método pertencente ao serviço da classe de service). Irei refatorar novamente....

2024-07-17 05:02 UTC, gustavojustino commented on src/main/java/com/petshopadmin/application/service/ServiceService.java
> +        validationService.validate(serviceDomain);
Refatorado

2024-07-17 05:09 UTC, gustavojustino commented on src/main/java/com/petshopadmin/application/service/ServiceService.java
> +        validationService.validate(serviceDomain);
Aqui tenho uma pergunta subjetiva, mas é literalmente uma dúvida, a minha lógica para isso, subentende que ter um validate na camada de serviço e um na controller garante robustez na API. Imaginei o cenário onde a API, pode não ser a única entrada de dados para o serviço. Pode haver outras fontes de dados ou outras integrações que chamam diretamente os métodos de serviço. Nesse caso, a validação na camada de serviço garante que todos esses pontos de entrada diferentes validem os dados consistentemente. Está errado neste contexto haver validate nas duas camadas?

2024-07-17 05:19 UTC, gustavojustino commented on src/main/java/com/petshopadmin/application/service/ServiceService.java
> +        validationService.validate(serviceDomain);
Neste cenário, chamar o validate dentro do método create, já garante a consistência de validação independentemente  de onde seja a  entrada de dados?

2024-07-17 05:56 UTC, gustavojustino commented on src/main/java/com/petshopadmin/configuration/ServiceConfiguration.java
> +    public ContractRepositoryDatabase contractRepositoryDatabase(ContractJPARepository contractJPARepository, ServiceConverterMapper serviceConverterMapper) {
Tava fazendo gambiarra pra funcionar e esqueci isso aqui desculpa

2024-07-26 01:39 UTC, MaironCosta approved these changes

2024-07-26 01:39 UTC, MaironCosta commented on src/main/java/com/petshopadmin/adapter/input/http/ServiceController.java
> +            serviceUserCase.validate(serviceDomain);
Tirar esse validate deste ponto.

2024-07-26 01:39 UTC, MaironCosta commented on src/main/java/com/petshopadmin/adapter/input/http/ServiceController.java
> +    @PostMapping(value = "/validate", produces = MediaType.APPLICATION_JSON_VALUE)
O padrão é `/validate-create`, assim como está no _petshop-api_.

2024-07-26 01:39 UTC, MaironCosta commented on src/main/java/com/petshopadmin/application/service/ServiceService.java
> +        validationService.validate(serviceDomain);
Exato. Se este ponto valida, a tua pergunta anterior já está respondida. Ou seja, inexista a necessidade de ter no controller, só se está executando a mesma coisa 2 vezes e onerando processamento. Só no create já é válido.

2024-07-26 01:39 UTC, MaironCosta commented on src/main/java/com/petshopadmin/application/service/ServiceService.java
> +        validationService.validate(serviceDomain);
Colocar a validação dentro deste método.

2024-07-26 01:39 UTC, MaironCosta commented on src/main/java/com/petshopadmin/adapter/output/repository/database/ServiceRepositoryDatabase.java
> +        if (ObjectUtils.isEmpty(serviceDatabase)) {
Nunca será `null` pois acabou de inicializar acima.

2024-07-26 01:39 UTC, MaironCosta commented on src/main/java/com/petshopadmin/adapter/output/repository/database/ServiceRepositoryDatabase.java
> +        if (!Objects.isNull(serviceDomain.getContract())) {
Se inexistir um `serviceDomain.getContract()` dará erro ao salvar, pois inexistirá referência no banco.

2024-07-26 01:39 UTC, MaironCosta commented on src/main/java/com/petshopadmin/application/service/ServiceService.java
> +        List<String> errors = new ArrayList<>();
Inicialize a lista de erros depois de checar se o `serviceDomain` é `null`. Da forma como está a lista de erro pode nunca ser utilizada e tu estará criando um objeto em memória que nunca será utilizado, assim só gastando memória e processamento em vão.

2024-07-26 01:39 UTC, MaironCosta commented on src/main/java/com/petshopadmin/application/service/ServiceService.java
> +        String name = StringUtils.trimToEmpty(serviceDomain.getName());
Aqui poderia ser: 

```
serviceDomain.setName(StringUtils.trimToEmpty(serviceDomain.getName()));
if (ObjectUtils.isEmpty(serviceDomain.getName())) {
            errors.add(ILLEGAL_ARGUMENT_NAME_EXCEPTION);
.
.
.
```

Assim poderia evitar o `else`.

https://pauloreal.medium.com/saiba-o-porque-voce-deveria-evitar-o-else-no-seu-codigo-792c8abc5683

2024-07-26 01:39 UTC, MaironCosta commented on src/main/java/com/petshopadmin/utils/converter/ServiceConverterMapper.java
> +public interface ServiceConverterMapper {
sim

2024-07-30 00:57 UTC, merged